---
- name: install required packages
  package:
    name:
      - composer
      - git

- name: install passbolt
  include: install.yml
  become: yes

- name: configure backup and restore process
  include: backup.yml
